name:                ch4
version:             0.1.0.0
github:              "githubuser/ch4"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/ch4#readme>

dependencies:
- base >= 4.7 && < 5
- yapb >= 0.2.3
- hspec

library:
  source-dirs: src

executables:
  expref-exe:
    main:                Main.hs
    source-dirs:         app/explicitrefslang
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch4

  impref-exe:
    main:                Main.hs
    source-dirs:         app/implicitrefslang
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch4 

  bothref-exe:
    main:                Main.hs
    source-dirs:         app/bothrefslang
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch4       

tests:
  explicitrefslang-test:
    main:                Spec.hs
    source-dirs:         
    - test/explicitrefslang
    - app/explicitrefslang
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch4

  implicitrefslang-test:
    main:                Spec.hs
    source-dirs:         
    - test/implicitrefslang
    - app/implicitrefslang
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch4

  bothrefslang-test:
    main:                Spec.hs
    source-dirs:         
    - test/bothrefslang
    - app/bothrefslang
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch4    
